/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface HoleConfig {
  'x' : bigint,
  'y' : bigint,
  'id' : string,
  'note' : string,
  'size' : bigint,
}
export interface HolePreset {
  'id' : string,
  'holeConfigs' : Array<HoleConfig>,
  'scaleMode' : ScaleMode,
  'name' : string,
  'octave' : bigint,
}
export interface HolePresetForm {
  'holeConfigs' : Array<HoleConfig>,
  'scaleMode' : ScaleMode,
  'name' : string,
  'octave' : bigint,
}
export interface Note {
  'fingering' : Array<string>,
  'duration' : bigint,
  'pitch' : string,
}
export interface OcarinaProfile {
  'id' : string,
  'holeConfigs' : Array<HoleConfig>,
  'scaleMode' : ScaleMode,
  'name' : string,
  'size' : SizePreset,
  'description' : string,
  'shape' : string,
  'category' : string,
  'octave' : bigint,
  'image' : ExternalBlob,
}
export interface OcarinaProfileForm {
  'holeConfigs' : Array<HoleConfig>,
  'scaleMode' : ScaleMode,
  'name' : string,
  'size' : SizePreset,
  'description' : string,
  'shape' : string,
  'category' : string,
  'octave' : bigint,
}
export interface PresetSong {
  'id' : string,
  'displayName' : string,
  'score' : Score,
}
export interface SampleAssignment { 'blob' : ExternalBlob, 'note' : string }
export type ScaleMode = { 'diatonic' : null } |
  { 'chromatic' : null };
export interface Score {
  'lyrics' : [] | [string],
  'name' : string,
  'notes' : Array<Note>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SizePreset = { 'alto' : null } |
  { 'bass' : null } |
  { 'lowBass' : null } |
  { 'soprano' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'favoriteScores' : Array<string>,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPresetSong' : ActorMethod<[string, string, Score], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkCreateOcarinaProfiles' : ActorMethod<
    [Array<[string, OcarinaProfileForm, ExternalBlob]>, string],
    undefined
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOcarinaProfile' : ActorMethod<
    [string, OcarinaProfileForm, ExternalBlob, string],
    undefined
  >,
  'deleteHolePreset' : ActorMethod<[string, string], undefined>,
  'deleteOcarinaProfile' : ActorMethod<[string, string], undefined>,
  'deleteSampleAssignment' : ActorMethod<[string], undefined>,
  'deleteScore' : ActorMethod<[string], undefined>,
  'getAllSampleAssignments' : ActorMethod<[], Array<SampleAssignment>>,
  'getAllScores' : ActorMethod<[], Array<Score>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHolePresets' : ActorMethod<[], Array<HolePreset>>,
  'getOcarinaProfile' : ActorMethod<[string], OcarinaProfile>,
  'getOcarinaProfiles' : ActorMethod<[], Array<OcarinaProfile>>,
  'getPresetSong' : ActorMethod<[string], PresetSong>,
  'getPresetSongList' : ActorMethod<
    [],
    Array<{ 'id' : string, 'displayName' : string }>
  >,
  'getSampleAssignment' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getScore' : ActorMethod<[string], Score>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'loadFingeringMap' : ActorMethod<[], Array<[string, Array<boolean>]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFingeringMap' : ActorMethod<
    [Array<[string, Array<boolean>]>],
    undefined
  >,
  'saveHolePreset' : ActorMethod<[HolePresetForm, string], undefined>,
  'saveScore' : ActorMethod<[string, Score], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOcarinaProfile' : ActorMethod<
    [string, OcarinaProfileForm, [] | [ExternalBlob], string],
    undefined
  >,
  'uploadSample' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];