/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Note = IDL.Record({
  'fingering' : IDL.Vec(IDL.Text),
  'duration' : IDL.Nat,
  'pitch' : IDL.Text,
});
export const Score = IDL.Record({
  'lyrics' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'notes' : IDL.Vec(Note),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HoleConfig = IDL.Record({
  'x' : IDL.Nat,
  'y' : IDL.Nat,
  'id' : IDL.Text,
  'note' : IDL.Text,
  'size' : IDL.Nat,
});
export const ScaleMode = IDL.Variant({
  'diatonic' : IDL.Null,
  'chromatic' : IDL.Null,
});
export const SizePreset = IDL.Variant({
  'alto' : IDL.Null,
  'bass' : IDL.Null,
  'lowBass' : IDL.Null,
  'soprano' : IDL.Null,
});
export const OcarinaProfileForm = IDL.Record({
  'holeConfigs' : IDL.Vec(HoleConfig),
  'scaleMode' : ScaleMode,
  'name' : IDL.Text,
  'size' : SizePreset,
  'description' : IDL.Text,
  'shape' : IDL.Text,
  'category' : IDL.Text,
  'octave' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SampleAssignment = IDL.Record({
  'blob' : ExternalBlob,
  'note' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'favoriteScores' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
});
export const HolePreset = IDL.Record({
  'id' : IDL.Text,
  'holeConfigs' : IDL.Vec(HoleConfig),
  'scaleMode' : ScaleMode,
  'name' : IDL.Text,
  'octave' : IDL.Nat,
});
export const OcarinaProfile = IDL.Record({
  'id' : IDL.Text,
  'holeConfigs' : IDL.Vec(HoleConfig),
  'scaleMode' : ScaleMode,
  'name' : IDL.Text,
  'size' : SizePreset,
  'description' : IDL.Text,
  'shape' : IDL.Text,
  'category' : IDL.Text,
  'octave' : IDL.Nat,
  'image' : ExternalBlob,
});
export const PresetSong = IDL.Record({
  'id' : IDL.Text,
  'displayName' : IDL.Text,
  'score' : Score,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const HolePresetForm = IDL.Record({
  'holeConfigs' : IDL.Vec(HoleConfig),
  'scaleMode' : ScaleMode,
  'name' : IDL.Text,
  'octave' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPresetSong' : IDL.Func([IDL.Text, IDL.Text, Score], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkCreateOcarinaProfiles' : IDL.Func(
      [
        IDL.Vec(IDL.Tuple(IDL.Text, OcarinaProfileForm, ExternalBlob)),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOcarinaProfile' : IDL.Func(
      [IDL.Text, OcarinaProfileForm, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'deleteHolePreset' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteOcarinaProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSampleAssignment' : IDL.Func([IDL.Text], [], []),
  'deleteScore' : IDL.Func([IDL.Text], [], []),
  'getAllSampleAssignments' : IDL.Func(
      [],
      [IDL.Vec(SampleAssignment)],
      ['query'],
    ),
  'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHolePresets' : IDL.Func([], [IDL.Vec(HolePreset)], ['query']),
  'getOcarinaProfile' : IDL.Func([IDL.Text], [OcarinaProfile], ['query']),
  'getOcarinaProfiles' : IDL.Func([], [IDL.Vec(OcarinaProfile)], ['query']),
  'getPresetSong' : IDL.Func([IDL.Text], [PresetSong], ['query']),
  'getPresetSongList' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'id' : IDL.Text, 'displayName' : IDL.Text }))],
      ['query'],
    ),
  'getSampleAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getScore' : IDL.Func([IDL.Text], [Score], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'loadFingeringMap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFingeringMap' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
      [],
      [],
    ),
  'saveHolePreset' : IDL.Func([HolePresetForm, IDL.Text], [], []),
  'saveScore' : IDL.Func([IDL.Text, Score], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOcarinaProfile' : IDL.Func(
      [IDL.Text, OcarinaProfileForm, IDL.Opt(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'uploadSample' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Note = IDL.Record({
    'fingering' : IDL.Vec(IDL.Text),
    'duration' : IDL.Nat,
    'pitch' : IDL.Text,
  });
  const Score = IDL.Record({
    'lyrics' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'notes' : IDL.Vec(Note),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HoleConfig = IDL.Record({
    'x' : IDL.Nat,
    'y' : IDL.Nat,
    'id' : IDL.Text,
    'note' : IDL.Text,
    'size' : IDL.Nat,
  });
  const ScaleMode = IDL.Variant({
    'diatonic' : IDL.Null,
    'chromatic' : IDL.Null,
  });
  const SizePreset = IDL.Variant({
    'alto' : IDL.Null,
    'bass' : IDL.Null,
    'lowBass' : IDL.Null,
    'soprano' : IDL.Null,
  });
  const OcarinaProfileForm = IDL.Record({
    'holeConfigs' : IDL.Vec(HoleConfig),
    'scaleMode' : ScaleMode,
    'name' : IDL.Text,
    'size' : SizePreset,
    'description' : IDL.Text,
    'shape' : IDL.Text,
    'category' : IDL.Text,
    'octave' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SampleAssignment = IDL.Record({
    'blob' : ExternalBlob,
    'note' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'favoriteScores' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
  });
  const HolePreset = IDL.Record({
    'id' : IDL.Text,
    'holeConfigs' : IDL.Vec(HoleConfig),
    'scaleMode' : ScaleMode,
    'name' : IDL.Text,
    'octave' : IDL.Nat,
  });
  const OcarinaProfile = IDL.Record({
    'id' : IDL.Text,
    'holeConfigs' : IDL.Vec(HoleConfig),
    'scaleMode' : ScaleMode,
    'name' : IDL.Text,
    'size' : SizePreset,
    'description' : IDL.Text,
    'shape' : IDL.Text,
    'category' : IDL.Text,
    'octave' : IDL.Nat,
    'image' : ExternalBlob,
  });
  const PresetSong = IDL.Record({
    'id' : IDL.Text,
    'displayName' : IDL.Text,
    'score' : Score,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const HolePresetForm = IDL.Record({
    'holeConfigs' : IDL.Vec(HoleConfig),
    'scaleMode' : ScaleMode,
    'name' : IDL.Text,
    'octave' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPresetSong' : IDL.Func([IDL.Text, IDL.Text, Score], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkCreateOcarinaProfiles' : IDL.Func(
        [
          IDL.Vec(IDL.Tuple(IDL.Text, OcarinaProfileForm, ExternalBlob)),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOcarinaProfile' : IDL.Func(
        [IDL.Text, OcarinaProfileForm, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'deleteHolePreset' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteOcarinaProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSampleAssignment' : IDL.Func([IDL.Text], [], []),
    'deleteScore' : IDL.Func([IDL.Text], [], []),
    'getAllSampleAssignments' : IDL.Func(
        [],
        [IDL.Vec(SampleAssignment)],
        ['query'],
      ),
    'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHolePresets' : IDL.Func([], [IDL.Vec(HolePreset)], ['query']),
    'getOcarinaProfile' : IDL.Func([IDL.Text], [OcarinaProfile], ['query']),
    'getOcarinaProfiles' : IDL.Func([], [IDL.Vec(OcarinaProfile)], ['query']),
    'getPresetSong' : IDL.Func([IDL.Text], [PresetSong], ['query']),
    'getPresetSongList' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'id' : IDL.Text, 'displayName' : IDL.Text }))],
        ['query'],
      ),
    'getSampleAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getScore' : IDL.Func([IDL.Text], [Score], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'loadFingeringMap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFingeringMap' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
        [],
        [],
      ),
    'saveHolePreset' : IDL.Func([HolePresetForm, IDL.Text], [], []),
    'saveScore' : IDL.Func([IDL.Text, Score], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOcarinaProfile' : IDL.Func(
        [IDL.Text, OcarinaProfileForm, IDL.Opt(ExternalBlob), IDL.Text],
        [],
        [],
      ),
    'uploadSample' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };