/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Note = IDL.Record({
  'fingering' : IDL.Vec(IDL.Text),
  'duration' : IDL.Nat,
  'pitch' : IDL.Text,
});
export const Score = IDL.Record({
  'lyrics' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'notes' : IDL.Vec(Note),
});
export const SizePreset = IDL.Variant({
  'alto' : IDL.Null,
  'bass' : IDL.Null,
  'lowBass' : IDL.Null,
  'soprano' : IDL.Null,
});
export const OcarinaProfileForm = IDL.Record({
  'name' : IDL.Text,
  'size' : SizePreset,
  'description' : IDL.Text,
  'shape' : IDL.Text,
  'category' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SampleAssignment = IDL.Record({
  'blob' : ExternalBlob,
  'note' : IDL.Text,
});
export const OcarinaProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'size' : SizePreset,
  'description' : IDL.Text,
  'shape' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const PresetSong = IDL.Record({
  'id' : IDL.Text,
  'displayName' : IDL.Text,
  'score' : Score,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPresetSong' : IDL.Func([IDL.Text, IDL.Text, Score], [], []),
  'bulkCreateOcarinaProfiles' : IDL.Func(
      [
        IDL.Vec(IDL.Tuple(IDL.Text, OcarinaProfileForm, ExternalBlob)),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createOcarinaProfile' : IDL.Func(
      [IDL.Text, OcarinaProfileForm, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'deleteOcarinaProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSampleAssignment' : IDL.Func([IDL.Text], [], []),
  'deleteScore' : IDL.Func([IDL.Text], [], []),
  'getAllSampleAssignments' : IDL.Func(
      [],
      [IDL.Vec(SampleAssignment)],
      ['query'],
    ),
  'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getOcarinaProfile' : IDL.Func([IDL.Text], [OcarinaProfile], ['query']),
  'getOcarinaProfiles' : IDL.Func([], [IDL.Vec(OcarinaProfile)], ['query']),
  'getPresetSong' : IDL.Func([IDL.Text], [PresetSong], ['query']),
  'getPresetSongList' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'id' : IDL.Text, 'displayName' : IDL.Text }))],
      ['query'],
    ),
  'getSampleAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getScore' : IDL.Func([IDL.Text], [Score], ['query']),
  'loadFingeringMap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
      ['query'],
    ),
  'saveFingeringMap' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
      [],
      [],
    ),
  'saveScore' : IDL.Func([IDL.Text, Score], [], []),
  'updateOcarinaProfile' : IDL.Func(
      [IDL.Text, OcarinaProfileForm, IDL.Opt(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'uploadSample' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Note = IDL.Record({
    'fingering' : IDL.Vec(IDL.Text),
    'duration' : IDL.Nat,
    'pitch' : IDL.Text,
  });
  const Score = IDL.Record({
    'lyrics' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'notes' : IDL.Vec(Note),
  });
  const SizePreset = IDL.Variant({
    'alto' : IDL.Null,
    'bass' : IDL.Null,
    'lowBass' : IDL.Null,
    'soprano' : IDL.Null,
  });
  const OcarinaProfileForm = IDL.Record({
    'name' : IDL.Text,
    'size' : SizePreset,
    'description' : IDL.Text,
    'shape' : IDL.Text,
    'category' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SampleAssignment = IDL.Record({
    'blob' : ExternalBlob,
    'note' : IDL.Text,
  });
  const OcarinaProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'size' : SizePreset,
    'description' : IDL.Text,
    'shape' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const PresetSong = IDL.Record({
    'id' : IDL.Text,
    'displayName' : IDL.Text,
    'score' : Score,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPresetSong' : IDL.Func([IDL.Text, IDL.Text, Score], [], []),
    'bulkCreateOcarinaProfiles' : IDL.Func(
        [
          IDL.Vec(IDL.Tuple(IDL.Text, OcarinaProfileForm, ExternalBlob)),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createOcarinaProfile' : IDL.Func(
        [IDL.Text, OcarinaProfileForm, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'deleteOcarinaProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSampleAssignment' : IDL.Func([IDL.Text], [], []),
    'deleteScore' : IDL.Func([IDL.Text], [], []),
    'getAllSampleAssignments' : IDL.Func(
        [],
        [IDL.Vec(SampleAssignment)],
        ['query'],
      ),
    'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getOcarinaProfile' : IDL.Func([IDL.Text], [OcarinaProfile], ['query']),
    'getOcarinaProfiles' : IDL.Func([], [IDL.Vec(OcarinaProfile)], ['query']),
    'getPresetSong' : IDL.Func([IDL.Text], [PresetSong], ['query']),
    'getPresetSongList' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'id' : IDL.Text, 'displayName' : IDL.Text }))],
        ['query'],
      ),
    'getSampleAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getScore' : IDL.Func([IDL.Text], [Score], ['query']),
    'loadFingeringMap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
        ['query'],
      ),
    'saveFingeringMap' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Bool)))],
        [],
        [],
      ),
    'saveScore' : IDL.Func([IDL.Text, Score], [], []),
    'updateOcarinaProfile' : IDL.Func(
        [IDL.Text, OcarinaProfileForm, IDL.Opt(ExternalBlob), IDL.Text],
        [],
        [],
      ),
    'uploadSample' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };