/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Note {
  'fingering' : Array<string>,
  'duration' : bigint,
  'pitch' : string,
}
export interface PresetSong {
  'id' : string,
  'displayName' : string,
  'score' : Score,
}
export interface SampleAssignment { 'blob' : ExternalBlob, 'note' : string }
export interface Score {
  'lyrics' : [] | [string],
  'name' : string,
  'notes' : Array<Note>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPresetSong' : ActorMethod<[string, string, Score], undefined>,
  'deleteSampleAssignment' : ActorMethod<[string], undefined>,
  'deleteScore' : ActorMethod<[string], undefined>,
  'getAllSampleAssignments' : ActorMethod<[], Array<SampleAssignment>>,
  'getAllScores' : ActorMethod<[], Array<Score>>,
  'getPresetSong' : ActorMethod<[string], PresetSong>,
  'getPresetSongList' : ActorMethod<
    [],
    Array<{ 'id' : string, 'displayName' : string }>
  >,
  'getSampleAssignment' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getScore' : ActorMethod<[string], Score>,
  'loadFingeringMap' : ActorMethod<[], Array<[string, Array<boolean>]>>,
  'saveFingeringMap' : ActorMethod<
    [Array<[string, Array<boolean>]>],
    undefined
  >,
  'saveScore' : ActorMethod<[string, Score], undefined>,
  'uploadSample' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];