/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    favoriteScores: Array<string>;
    name: string;
}
export interface Note {
    fingering: Array<string>;
    duration: bigint;
    pitch: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface HoleConfig {
    x: bigint;
    y: bigint;
    id: string;
    note: string;
    size: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Score {
    lyrics?: string;
    name: string;
    notes: Array<Note>;
}
export interface HolePreset {
    id: string;
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    octave: bigint;
}
export interface PresetSong {
    id: string;
    displayName: string;
    score: Score;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OcarinaProfile {
    id: string;
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    size: SizePreset;
    description: string;
    shape: string;
    category: string;
    octave: bigint;
    image: ExternalBlob;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface OcarinaProfileForm {
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    size: SizePreset;
    description: string;
    shape: string;
    category: string;
    octave: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SampleAssignment {
    blob: ExternalBlob;
    note: string;
}
export interface HolePresetForm {
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    octave: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ScaleMode {
    diatonic = "diatonic",
    chromatic = "chromatic"
}
export enum SizePreset {
    alto = "alto",
    bass = "bass",
    lowBass = "lowBass",
    soprano = "soprano"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPresetSong(id: string, displayName: string, score: Score): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkCreateOcarinaProfiles(entries: Array<[string, OcarinaProfileForm, ExternalBlob]>, password: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOcarinaProfile(id: string, profileData: OcarinaProfileForm, image: ExternalBlob, password: string): Promise<void>;
    deleteHolePreset(id: string, password: string): Promise<void>;
    deleteOcarinaProfile(id: string, password: string): Promise<void>;
    deleteSampleAssignment(note: string): Promise<void>;
    deleteScore(name: string): Promise<void>;
    getAllSampleAssignments(): Promise<Array<SampleAssignment>>;
    getAllScores(): Promise<Array<Score>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHolePresets(): Promise<Array<HolePreset>>;
    getOcarinaProfile(id: string): Promise<OcarinaProfile>;
    getOcarinaProfiles(): Promise<Array<OcarinaProfile>>;
    getPresetSong(id: string): Promise<PresetSong>;
    getPresetSongList(): Promise<Array<{
        id: string;
        displayName: string;
    }>>;
    getSampleAssignment(note: string): Promise<ExternalBlob | null>;
    getScore(name: string): Promise<Score>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    loadFingeringMap(): Promise<Array<[string, Array<boolean>]>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveFingeringMap(newMap: Array<[string, Array<boolean>]>): Promise<void>;
    saveHolePreset(preset: HolePresetForm, password: string): Promise<void>;
    saveScore(name: string, score: Score): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateOcarinaProfile(id: string, updatedProfile: OcarinaProfileForm, image: ExternalBlob | null, password: string): Promise<void>;
    uploadSample(note: string, blob: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, HoleConfig as _HoleConfig, HolePreset as _HolePreset, HolePresetForm as _HolePresetForm, Note as _Note, OcarinaProfile as _OcarinaProfile, OcarinaProfileForm as _OcarinaProfileForm, PresetSong as _PresetSong, SampleAssignment as _SampleAssignment, ScaleMode as _ScaleMode, Score as _Score, SizePreset as _SizePreset, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPresetSong(arg0: string, arg1: string, arg2: Score): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPresetSong(arg0, arg1, to_candid_Score_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPresetSong(arg0, arg1, to_candid_Score_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkCreateOcarinaProfiles(arg0: Array<[string, OcarinaProfileForm, ExternalBlob]>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateOcarinaProfiles(await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateOcarinaProfiles(await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOcarinaProfile(arg0: string, arg1: OcarinaProfileForm, arg2: ExternalBlob, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOcarinaProfile(arg0, to_candid_OcarinaProfileForm_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOcarinaProfile(arg0, to_candid_OcarinaProfileForm_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteHolePreset(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHolePreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHolePreset(arg0, arg1);
            return result;
        }
    }
    async deleteOcarinaProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOcarinaProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOcarinaProfile(arg0, arg1);
            return result;
        }
    }
    async deleteSampleAssignment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSampleAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSampleAssignment(arg0);
            return result;
        }
    }
    async deleteScore(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScore(arg0);
            return result;
        }
    }
    async getAllSampleAssignments(): Promise<Array<SampleAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSampleAssignments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSampleAssignments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllScores(): Promise<Array<Score>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScores();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScores();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHolePresets(): Promise<Array<HolePreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolePresets();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolePresets();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOcarinaProfile(arg0: string): Promise<OcarinaProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOcarinaProfile(arg0);
                return from_candid_OcarinaProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOcarinaProfile(arg0);
            return from_candid_OcarinaProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOcarinaProfiles(): Promise<Array<OcarinaProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOcarinaProfiles();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOcarinaProfiles();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresetSong(arg0: string): Promise<PresetSong> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresetSong(arg0);
                return from_candid_PresetSong_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresetSong(arg0);
            return from_candid_PresetSong_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPresetSongList(): Promise<Array<{
        id: string;
        displayName: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresetSongList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresetSongList();
            return result;
        }
    }
    async getSampleAssignment(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleAssignment(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleAssignment(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScore(arg0: string): Promise<Score> {
        if (this.processError) {
            try {
                const result = await this.actor.getScore(arg0);
                return from_candid_Score_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScore(arg0);
            return from_candid_Score_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async loadFingeringMap(): Promise<Array<[string, Array<boolean>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.loadFingeringMap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadFingeringMap();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveFingeringMap(arg0: Array<[string, Array<boolean>]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFingeringMap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFingeringMap(arg0);
            return result;
        }
    }
    async saveHolePreset(arg0: HolePresetForm, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHolePreset(to_candid_HolePresetForm_n48(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHolePreset(to_candid_HolePresetForm_n48(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async saveScore(arg0: string, arg1: Score): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScore(arg0, to_candid_Score_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScore(arg0, to_candid_Score_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateOcarinaProfile(arg0: string, arg1: OcarinaProfileForm, arg2: ExternalBlob | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOcarinaProfile(arg0, to_candid_OcarinaProfileForm_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOcarinaProfile(arg0, to_candid_OcarinaProfileForm_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async uploadSample(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSample(arg0, await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSample(arg0, await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HolePreset_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HolePreset): HolePreset {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_OcarinaProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OcarinaProfile): Promise<OcarinaProfile> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PresetSong_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PresetSong): PresetSong {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_SampleAssignment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleAssignment): Promise<SampleAssignment> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ScaleMode_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScaleMode): ScaleMode {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Score_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Score): Score {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SizePreset_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SizePreset): SizePreset {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    note: string;
}): Promise<{
    blob: ExternalBlob;
    note: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.blob),
        note: value.note
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lyrics: [] | [string];
    name: string;
    notes: Array<_Note>;
}): {
    lyrics?: string;
    name: string;
    notes: Array<Note>;
} {
    return {
        lyrics: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lyrics)),
        name: value.name,
        notes: value.notes
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    holeConfigs: Array<_HoleConfig>;
    scaleMode: _ScaleMode;
    name: string;
    octave: bigint;
}): {
    id: string;
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    octave: bigint;
} {
    return {
        id: value.id,
        holeConfigs: value.holeConfigs,
        scaleMode: from_candid_ScaleMode_n35(_uploadFile, _downloadFile, value.scaleMode),
        name: value.name,
        octave: value.octave
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    holeConfigs: Array<_HoleConfig>;
    scaleMode: _ScaleMode;
    name: string;
    size: _SizePreset;
    description: string;
    shape: string;
    category: string;
    octave: bigint;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    size: SizePreset;
    description: string;
    shape: string;
    category: string;
    octave: bigint;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        holeConfigs: value.holeConfigs,
        scaleMode: from_candid_ScaleMode_n35(_uploadFile, _downloadFile, value.scaleMode),
        name: value.name,
        size: from_candid_SizePreset_n39(_uploadFile, _downloadFile, value.size),
        description: value.description,
        shape: value.shape,
        category: value.category,
        octave: value.octave,
        image: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    displayName: string;
    score: _Score;
}): {
    id: string;
    displayName: string;
    score: Score;
} {
    return {
        id: value.id,
        displayName: value.displayName,
        score: from_candid_Score_n26(_uploadFile, _downloadFile, value.score)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diatonic: null;
} | {
    chromatic: null;
}): ScaleMode {
    return "diatonic" in value ? ScaleMode.diatonic : "chromatic" in value ? ScaleMode.chromatic : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alto: null;
} | {
    bass: null;
} | {
    lowBass: null;
} | {
    soprano: null;
}): SizePreset {
    return "alto" in value ? SizePreset.alto : "bass" in value ? SizePreset.bass : "lowBass" in value ? SizePreset.lowBass : "soprano" in value ? SizePreset.soprano : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n47(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SampleAssignment>): Promise<Array<SampleAssignment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SampleAssignment_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Score>): Array<Score> {
    return value.map((x)=>from_candid_Score_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HolePreset>): Array<HolePreset> {
    return value.map((x)=>from_candid_HolePreset_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OcarinaProfile>): Promise<Array<OcarinaProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OcarinaProfile_n37(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HolePresetForm_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HolePresetForm): _HolePresetForm {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_OcarinaProfileForm_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OcarinaProfileForm): _OcarinaProfileForm {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ScaleMode_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScaleMode): _ScaleMode {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Score_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Score): _Score {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SizePreset_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SizePreset): _SizePreset {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    size: SizePreset;
    description: string;
    shape: string;
    category: string;
    octave: bigint;
}): {
    holeConfigs: Array<_HoleConfig>;
    scaleMode: _ScaleMode;
    name: string;
    size: _SizePreset;
    description: string;
    shape: string;
    category: string;
    octave: bigint;
} {
    return {
        holeConfigs: value.holeConfigs,
        scaleMode: to_candid_ScaleMode_n16(_uploadFile, _downloadFile, value.scaleMode),
        name: value.name,
        size: to_candid_SizePreset_n18(_uploadFile, _downloadFile, value.size),
        description: value.description,
        shape: value.shape,
        category: value.category,
        octave: value.octave
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    holeConfigs: Array<HoleConfig>;
    scaleMode: ScaleMode;
    name: string;
    octave: bigint;
}): {
    holeConfigs: Array<_HoleConfig>;
    scaleMode: _ScaleMode;
    name: string;
    octave: bigint;
} {
    return {
        holeConfigs: value.holeConfigs,
        scaleMode: to_candid_ScaleMode_n16(_uploadFile, _downloadFile, value.scaleMode),
        name: value.name,
        octave: value.octave
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lyrics?: string;
    name: string;
    notes: Array<Note>;
}): {
    lyrics: [] | [string];
    name: string;
    notes: Array<_Note>;
} {
    return {
        lyrics: value.lyrics ? candid_some(value.lyrics) : candid_none(),
        name: value.name,
        notes: value.notes
    };
}
async function to_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, OcarinaProfileForm, ExternalBlob]): Promise<[string, _OcarinaProfileForm, _ExternalBlob]> {
    return [
        value[0],
        to_candid_OcarinaProfileForm_n14(_uploadFile, _downloadFile, value[1]),
        await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[2])
    ];
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScaleMode): {
    diatonic: null;
} | {
    chromatic: null;
} {
    return value == ScaleMode.diatonic ? {
        diatonic: null
    } : value == ScaleMode.chromatic ? {
        chromatic: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SizePreset): {
    alto: null;
} | {
    bass: null;
} | {
    lowBass: null;
} | {
    soprano: null;
} {
    return value == SizePreset.alto ? {
        alto: null
    } : value == SizePreset.bass ? {
        bass: null
    } : value == SizePreset.lowBass ? {
        lowBass: null
    } : value == SizePreset.soprano ? {
        soprano: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, OcarinaProfileForm, ExternalBlob]>): Promise<Array<[string, _OcarinaProfileForm, _ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await to_candid_tuple_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
